<?php
/**
* Data file generated by EMBFileMenu (ArrayModel)
* Date: June 27, 2013, 8:14 am
*
* Allowed data structure:
*   array(
*       'menuid' => 'menuid',
*       'titles' => 'titles',
*       'descriptions' => 'descriptions',
*       'descriptionashint' => 'descriptionashint',
*       'visible' => 'visible',
*       'locked' => 'locked',
*       'sortposition' => 'sortposition',
*       'maxdepth' => 'maxdepth',
*       'icon' => 'icon',
*       'nestedconfig' => 'nestedconfig',
*       'userroles' => 'userroles',
*       'scenarios' => 'scenarios',
*       'adminroles' => 'adminroles',
*       'created' => 'created',
*       'createduser' => 'createduser',
*       'modified' => 'modified',
*       'modifieduser' => 'modifieduser',
*   )
*/
return array(
	0 => array(
		'menuid' => 'main',
		'titles' => array(
			'en_us' => 'Main menu',
			'de' => 'Hauptmenü',
		),
		'descriptions' => array(
			'en_us' => '',
			'de' => '',
		),
		'descriptionashint' => true,
		'visible' => true,
		'locked' => false,
		'sortposition' => 0,
		'maxdepth' => 3,
		'icon' => '',
		'userroles' => '',
		'scenarios' => '',
		'adminroles' => '',
		'created' => 'Jun 27, 2013 8:14:47 AM',
		'createduser' => 'guest',
	),
	1 => array(
		'menuid' => 'sidebar_left',
		'titles' => array(
			'en_us' => 'Sidebar left',
			'de' => 'Seitenleiste links',
		),
		'descriptions' => array(
			'en_us' => '',
			'de' => '',
		),
		'descriptionashint' => true,
		'visible' => true,
		'locked' => false,
		'sortposition' => 0,
		'maxdepth' => 2,
		'icon' => '',
		'userroles' => '',
		'scenarios' => '',
		'adminroles' => '',
		'created' => 'Jun 27, 2013 8:14:48 AM',
		'createduser' => 'guest',
	),
);
